### ISSUE TITLE
Fix link to phylotree from gene record page so that gene is highlighted

### ISSUE THREAD

**Issue by ekcannon** [legumeinfo/tripal_gene#3]
The desired behavior can be achieved either by linking with the feature.unique_name for the gene alone as with:
    /chado_gene_phylotree_v2/Glyma.15G026400.Wm82.a2.v1
(the server side code will do the gene family lookup for the gene in this case)
or you can use both the family and the gene feature.name
    chado_gene_phylotree_v2?family=phytozome_10_2.59289650&gene_name=glyma.Glyma.15G026400
(this form allows you to specify multiple genes when appropriate, though is not needed in your case)

The link will need to be constructed using db.urlprefix for 'LegumeInfo_gene_families'.

**Comment by isumoc** [comment]
fixed via 
https://github.com/legumeinfo/tripal_gene/commit/c30b5d852d02f8525eb777dc8fa79c2f1975ab77
