### ISSUE TITLE
Add domain links to gene model record page and search results

### ISSUE THREAD

**Issue by ekcannon** [legumeinfo/tripal_gene#5]
PFxxxx: PFAM
PTHRxxxxx: PANTHER: db.name=PANTHER; Ignore accessions with suffixes, e.g. ":SF47"
PR0xxxx: PRINTS? no urlprefix for this db --> IGNORE
PSxxxxx: PROSITE
SMxxxxx: SMART; db.urlprefix needs to be 'http://smart.embl.de/smart/do_annotation.pl?DOMAIN='
SSFxxxxx: SUPERFAMILY (link with xxxxx part)
G3DSA:x.x.x.x: CATHDB (link with x.x.x.x part)
TIGRxxxxx: TAGRFAM

Ignore all others, e.g. 'Coil'

**Comment by isumoc** [comment]
fixed via https://github.com/legumeinfo/tripal_gene/commit/003f36c3f937806ab1983216debbfb30844c5678
